### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by NO-UUID** [GreenSurvivors/Padlock#15]
Would suggest changing

PadlockAPI#isMember(@NotNull Block block, @NotNull Player player)

to 

PadlockAPI#isMember(@NotNull Block block, @NotNull OfflinePlayer offlinePlayer)

which would allow plugins that might hook into Padlock to check if offline players can access specific block.

---------------

It would probably be good idea to add some more aliases from similar plugins, just so it makes life a bit easier for players:

aliases: [ lock, padlock, lockit, lockette, deadbolt ]

---------------

Updating signs, not sure how signs are currently updated but from what I could see when testing, usernames on signs are not automatically updated? I'd suggest maybe adding feature where the sign would be updated on interact if player is online and has clicked on outdated sign?

**Comment by FireInstall** [comment]
Using Offlineplayer might not be the best idea, since paper plans to decouple it from the player class in the future.
I would rather just use UUIDs instead.

---

We already have alias, `lock, padlock, lockit`, deadbolt I'm not sure about, since it's a whole different plugin with a whole different approach. Using Lockette old alias is fine since this is a successor of Lockette(Pro).

---

The plugin doesn't keep track of all signs, so clicking one sign can never update all at once.
All names are purely visual and even if an old name gets displayed, there shouldn't be an issue. They will get updated as soon as something of this lock get changed - like in case adding a member should resolve all names.
However, I'm not sure how I feel about just selecting the sign to update the display of it.

Are you expecting your users to change their names a lot?

**Comment by NO-UUID** [comment]
Got it.

I guess then the issue could only be last part. They change usernames quite often on an active server and then bug staff members about outdated usernames.

> The plugin doesn't keep track of all signs, so clicking one sign can never update all at once.

I think just updating that one sign that is being clicked on / interacted with (if the player is online) would be enough?

On a side note, I did build and test dev branch and it appears it would prevent players from using water/lava buckets and config loading is broken for some of the things, QuickProtectOption.OFF don't work and defaults instead, think HopperMinecartBlockedOption.REMOVE is broken too if the admin wants to just disable it. (on latest paper 1.21.1)

**Comment by FireInstall** [comment]
How about I add an subcommand then? This way it can't get mindlessly spammend nor do unexpected things happen.

---
Fixed the config options and buckets.

Thanks for testing and reporting 👍
